create database CLIENTES;
use CLIENTES;
CREATE TABLE PROVINCIAS(
    PRO_ID INTEGER (4) NOT NULL AUTO_INCREMENT,
    PRO_NOMBRE VARCHAR (40),
    PRIMARY KEY (PRO_ID)
    );

CREATE TABLE LOCALIDADES(
    LOC_ID INTEGER (4) NOT NULL AUTO_INCREMENT,
    LOC_NOMBRE VARCHAR (40),
    LOC_PRO_ID VARCHAR (4),
    PRIMARY KEY (LOC_ID),
    FOREIGN KEY (PRO_ID)
    );
    CREATE TABLE CLIENTES(
    CLI_ID INTEGER (4) NOT NULL AUTO_INCREMENT,
    CLI_NOMBRE VARCHAR (40),
    CLI_APELLIDO VARCHAR (30),
    CLI_CUIT VARCHAR (11),
    CLI_DIRECCION VARCHAR (30),
    CLI_LOC_ID VARCHAR (4),
    CLI_RAZONSOC VARCHAR (20),
    PRIMARY KEY (CLI_ID)
    );